name: path_finders
description: Find the path to your friends.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.1.0
  http: ^1.1.0
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.3

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
