name: path_finders
description: Find the path to your friends.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dynamic_color: ^1.6.8
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.1.0
  http: ^1.1.0
  path_provider: ^2.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  test: ^1.24.3

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/compass/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
